//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TrayPanel.rc
//
#define IDD_TRAYPANEL_DIALOG            102
#define IDR_SETTING                     103
#define IDR_LANG_CH                     104
#define IDR_LANG_ENG                    105
#define IDR_MANIFEST1                   129
#define IDR_MENU_POPUP                  130
#define IDD_DLG_MAIN                    131
#define IDD_DLG_ADVANCED                132
#define IDD_DLG_WORD                    133
#define IDD_DLG_DIC                     133
#define IDI_ICON1                       135
#define IDR_MAINFRAME                   135
#define IDD_DLG_ABOUT                   135
#define IDI_ICON2                       137
#define IDI_DISABLE                     137
#define IDD_DLG_COMPSEE                 141
#define IDD_DLG_TRANS                   142
#define IDD_DLG_SUGGESTION              143
#define IDD_DLG_KEY                     144
#define IDI_ICON_WRONG                  150
#define IDI_ICON_RIGHT                  151
#define IDR_PNG1                        160
#define IDC_TAB_MAIN                    1000
#define IDC_CHECK_ENABLE                1013
#define IDAPPLY                         1015
#define IDC_LIST_WORD_L                 1017
#define IDC_LIST_WORD_R                 1018
#define IDC_BTN_WORD_OK                 1020
#define IDC_BTN_WORD_CANCEL             1021
#define IDC_BTN_WORD_SCAN               1022
#define IDC_BTN_GETWORDDIC              1023
#define IDC_HOTKEY                      1031
#define IDC_BTN_PHS_UP                  1033
#define IDC_BTN_UP                      1033
#define IDC_BTN_PHS_DOWN                1034
#define IDC_BTN_DOWN                    1034
#define IDC_EDIT_WORDNUM                1036
#define IDC_EDIT_PHRASENUM              1037
#define IDC_EDIT_WORDCACHE              1038
#define IDC_SLI_WORDNUM                 1039
#define IDC_SLI_PHRASENUM               1040
#define IDC_AUTORUN                     1041
#define IDC_SLI_WORDCACHE               1041
#define IDC_AUTOENABLE                  1042
#define IDC_SLI_PHRASESORT              1042
#define IDC_BOOLEAN                     1043
#define IDC_PHRASESORT                  1043
#define IDC_EDIT_PHRASESORT             1043
#define IDC_EDIT_ABOUT                  1044
#define IDC_COMBO_TAB                   1047
#define IDC_COMBO_ENTER                 1048
#define IDC_COMBO_USER_KF               1049
#define IDC_COMBO_USER_VK               1050
#define IDC_COMBO_USER_MF               1051
#define IDC_COMBO_SHIFT                 1051
#define IDC_COMBO_THEME                 1054
#define IDC_CHECK_SHADOW                1055
#define IDC_BUTTON1                     1056
#define IDC_BTN_CA                      1056
#define IDC_BUTTON_REG                  1056
#define IDC_BTN_UCA                     1057
#define IDC_EDIT_WORDINFO               1058
#define IDC_EDIT_PHSINFO                1059
#define IDC_LIST_DIC                    1060
#define IDC_LIST_TRANS                  1061
#define IDC_EDIT_INFO                   1062
#define IDC_EDIT_HIDE                   1065
#define IDC_SPIN_HIDE                   1066
#define IDC_EDIT_USER                   1067
#define IDC_EDIT_START                  1067
#define IDC_EDIT_SN                     1068
#define IDC_SPIN_START                  1068
#define IDC_PICTURE                     1070
#define IDC_CHECK_ENTRANS               1071
#define IDC_CHECK_                      1072
#define IDC_CHECK_UNMATCH               1072
#define IDC_CHECK_PROPHONLY             1073
#define IDC_BUTTON_GETSN                1074
#define IDC_COMBO_FONT                  1075
#define IDC_EDIT_FONTSIZE               1076
#define IDC_CHECK_BOLD                  1077
#define IDC_CHECK_ITALIC                1078
#define IDC_CHECK_EC                    1079
#define IDC_COMBO_CLEAR                 1079
#define IDC_CHECK_PC                    1080
#define IDC_EDIT_EC                     1081
#define IDC_EDIT_TMOUT                  1082
#define IDC_SPIN_EC                     1083
#define IDC_SPIN_TMOUT                  1084
#define IDC_EDIT_ECMAX                  1085
#define IDC_SPIN_ECMAX                  1086
#define IDC_EDIT_PC                     1087
#define IDC_EDIT1                       1087
#define IDC_EDIT_TRIALDAY               1087
#define IDC_SPIN_PC                     1088
#define IDC_RADIO_TRADITIONAL           1088
#define IDC_EDIT_PCMAX                  1089
#define IDC_RADIO_EXPRESS               1089
#define IDC_SPIN_PCMAX                  1090
#define IDC_CHECK_NEEDSPACE             1090
#define IDC_RADIO_SUB3                  1091
#define IDC_RADIO_SUB2                  1092
#define IDC_CHECK_INTER                 1093
#define IDC_RADIO_SUB1                  1094
#define IDC_RADIO_BRA3                  1095
#define IDC_RADIO_BRA2                  1096
#define IDC_SPIN                        1096
#define IDC_SPIN_FONT                   1096
#define IDC_RADIO_BRA1                  1097
#define IDC_STC_ABTUS                   1097
#define IDC_COMBO_LAN                   1098
#define IDC_STC_ENBALL                  1099
#define IDC_STC_BOOTSEL                 1100
#define IDC_STC_THEME                   1101
#define IDC_STC_PERFORM                 1102
#define IDC_STC_OPTI                    1103
#define IDC_STC_MWHN                    1104
#define IDC_STC_MPHN                    1105
#define IDC_STC_WDC                     1106
#define IDC_STC_PSD                     1107
#define IDC_STC_MISC                    1108
#define IDC_STC_SHF                     1109
#define IDC_STC_HWS                     1110
#define IDC_STC_PDI                     1111
#define IDC_STC_WI                      1112
#define IDC_STC_PI                      1113
#define IDC_STC_IC                      1114
#define IDC_STC_ACKS                    1115
#define IDC_STC_TKF                     1116
#define IDC_STC_EKF                     1117
#define IDC_STC_SKF                     1118
#define IDC_STC_UDK                     1119
#define IDC_STC_UDKF                    1120
#define IDC_STC_CB                      1121
#define IDC_STC_COLOR                   1122
#define IDC_STC_FONT                    1123
#define IDC_STC_CLEAR                   1124
#define IDC_STC_SIZE                    1125
#define IDC_STC_TWM                     1126
#define IDC_STC_HOTKEY                  1127
#define IDC_STC_ECS                     1128
#define IDC_STC_SEC                     1129
#define IDC_STC_MECS                    1130
#define IDC_STC_PCS                     1131
#define IDC_STC_SPC                     1132
#define IDC_STC_MPCS                    1133
#define IDC_STC_TDI                     1134
#define IDC_STC_TI                      1135
#define IDC_STC_SF1                     1136
#define IDC_STC_SF2                     1137
#define ID_POPUP_SHOW                   32771
#define ID_POPUP_EXIT                   32772
#define ID_POPUP_ENABLE                 32773
#define ID_POPUP_COMPATIBLEMODE         32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
